# Default values for travel-control.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

username: user1

ossm_ingress: userX-ingress-istio-gateway.apps.example.com
